version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - facturacion-network

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - facturacion-network

networks:
  facturacion-network:
    driver: bridge