server {
    listen 80;
    location / {
        proxy_pass http://frontend:4200; # Nombre del servicio en docker-compose
    }
    location /api/ {
        proxy_pass http://backend:8081/; # Ajusta el puerto a 8081 si es ese
    }
}